# Generated by Django 5.0.4 on 2024-04-14 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('K', 'Koshi Province'), ('J', 'Janaki Province'), ('B', 'Bagmati Province'), ('G', 'Gandaki Province'), ('L', 'Lumbini Province'), ('K', 'Karnali Province'), ('S', 'Sudurpashchim Province')], max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('profile_pic', models.ImageField(default='profile/profile.png', upload_to='profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
